conversor/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name = 'conversor'

urlpatterns = [
	path('', views.home, name = 'homepage'),
	url('audio/', views.ttsapi.as_view(), name='audio'),
]

conversortts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('conversor.urls', namespace = 'conversor'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversor/models.py
from django.db import models

class Audio(models.Model):

	idiomas = [('de', 'Alemão'),
				('ca', 'Catalão'),
				('zn-cn', 'Chinês'),
				('ko', 'Coreano'),
				('es-es', 'Espanhol'),
				('fr-fr', 'Francês'),
				('en-ca', 'Inglês (Canadá)'),
			    ('en-us', 'Inglês (EUA)'),
			    ('en-uk', 'Inglês (Reino Unido)'),
			    ('ja', 'Japonês'),
			    ('la', 'Latim'),
				('pt-br', 'Português (BR)'), 
				('pt-pt', 'Português (PT)'),
				('ru', 'Russo')]

	nome_do_arquivo = models.CharField(max_length = 255, 
							help_text = 'Não utilize acento no nome do arquivo.')

	texto = models.TextField()

	idioma = models.CharField(
		max_length = 255,
		choices = idiomas,
		default = ('pt-br', 'Português')
		)

	def __str__(self):
		return self.nome_do_arquivo

conversor/forms.py
from django import forms
from .models import Audio

class AudioForm(forms.ModelForm):

	class Meta:
		model = Audio
		fields = '__all__'

conversor/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from .models import Audio
from .forms import AudioForm

import os
from gtts import gTTS

from rest_framework import generics
from .serializers import AudioSerializer

def home(request):
	if request.method == 'POST':
		form = AudioForm(request.POST)
		if form.is_valid():
			form.save()
			audios = Audio.objects.all()
			for audio in audios:
				arquivo = gTTS(audio.texto, lang = audio.idioma)
				arquivo.save('conversor/media/{}.mp3'.format(audio.nome_do_arquivo))			
			return render(request, 'conversor/audio.html', {'audios': audios})
	else:
		for file in os.listdir('conversor/media'):
			if file[-1:-4:-1] == '3pm':
				os.remove('conversor/media/{}'.format(file))
					
		audios = Audio.objects.all()
		for audio in audios:
			audio.delete()

		form = AudioForm()
		return render(request, 'conversor/index.html', {'form': form})

class ttsapi(generics.ListCreateAPIView):
	queryset = Audio.objects.all()
	serializer_class = AudioSerializer
	

'''def download(request, id):
	audio = get_object_or_404(Audio, pk = id)
	myfile = open('media/{}.mp3'.format(audio.nome_do_arquivo), 'rb')
	response = HttpResponse(myfile, content_type = 'audio/mpeg3')
	response['Content-Disposition'] = u"attachment; filename = %s.mp3" % audio.nome_do_arquivo
	return response'''

conversor/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
	
	<head>
		
		<title>{% block title %}{% endblock %}</title>
		<meta charset="utf-8">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link rel="shortcut icon" type="image/png" href="{% static 'icone.png' %}"/>
	
	</head>
	
	<body>

		<div class="bodycontent">
			
			<div class="topo">
				<a href="{% url 'conversor:homepage' %}">
					<p class="nome">Conversor Text-To-Speech</p>
				</a>
			</div>

			{% block content %}{% endblock %}
		</div>

	</body>

	<footer>
		
		<p>Desenvolvido por: Raphael Gibson</p>
		<h2>Conversor Text-To-Speech</h2>
		<p>2019</p>

	</footer>

	<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

</html>

conversor/templates/conversor/audio.html
{% extends 'base.html' %}

{% block title %} Conversor TTS {% endblock %}

{% block content %}

<div class="visualizacao">
	{% for audio in audios %}

	<h2>Nome do arquivo:</h2>

	<p class="text">&nbsp;&nbsp; {{audio.nome_do_arquivo}}.mp3</p>

	<h2>Texto convertido em áudio ({{audio.get_idioma_display}}):</h2>

	<p class="text">&nbsp;&nbsp; {{audio.texto}}</p>
	
	<audio id="audio" controls name="media" data-vscid="1lssv8tbt">
		<source src="../../media/{{audio.nome_do_arquivo}}.mp3" type="audio/mpeg">
		Seu navegador não suporta áudio com HTML5.
	</audio>

	<p id="download">Para baixar o áudio, clique nos 3 pontos do player de áudio e em seguida clique em "Fazer o download".</p>

	<div class="divbotoes">
		
		<a href="{% url 'conversor:homepage' %}"><span class="botao">Gerar novo áudio</span></a>

	</div>

	{% endfor %}
</div>

{% endblock %}

conversor/templates/conversor/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Conversor TTS {% endblock %}

{% block content %}
	
<p class="explicacao">Este conversor de texto para áudio gera um arquivo de áudio baseado no texto digitado e o disponibiliza para download no formato MP3.</p>

<div>
	<div class="container formu">
		<div class="row">
			<div class="col-xs-4">
				<h2>Texto a ser convertido:</h2>
				<form method="POST" autocomplete="off">
					{% csrf_token %}
					{{form|crispy}}
					<input class="gerar" type="submit" value="Gerar áudio">
				</form>
			</div>
		</div>
	</div>

</div>

{% endblock %}